import {
  AutomationStatus,
  CurrentRunCaseStatus,
  TestCasePriority,
  TestCaseSeverity,
  TestCaseType,
  type RunCaseFieldsFragment,
  type TestCaseFieldsFragment,
} from '@/shared/api/graphql';

export const testCaseFixture: TestCaseFieldsFragment = {
  id: 'case-1',
  projectId: 'project-1',
  suiteId: 'suite-1',
  caseNumber: 1,
  displayId: 'WEB-1',
  title: 'Пользователь входит с корректными данными',
  description: 'Проверка основной формы входа',
  preconditions: 'Пользователь зарегистрирован',
  postconditions: null,
  priority: TestCasePriority.High,
  severity: TestCaseSeverity.Critical,
  type: TestCaseType.Smoke,
  automationStatus: AutomationStatus.Manual,
  assigneeId: null,
  estimatedDurationSeconds: 180,
  createdBy: 'user-1',
  archivedAt: null,
  createdAt: '2026-08-20T08:00:00Z',
  updatedAt: '2026-08-20T09:00:00Z',
  tags: [
    {
      id: 'tag-1',
      projectId: 'project-1',
      name: 'Smoke',
      createdAt: '2026-08-20T08:00:00Z',
      updatedAt: '2026-08-20T08:00:00Z',
    },
  ],
  steps: [
    {
      id: 'step-1',
      testCaseId: 'case-1',
      position: 0,
      action: 'Открыть форму входа',
      testData: 'qa@example.com',
      expectedResult: 'Форма отображается',
      createdAt: '2026-08-20T08:00:00Z',
      updatedAt: '2026-08-20T08:00:00Z',
    },
  ],
};

export const runCaseFixture: RunCaseFieldsFragment = {
  id: 'run-case-1',
  testRunId: 'run-1',
  projectId: 'project-1',
  sourceTestCaseId: 'case-1',
  assigneeId: null,
  caseNumber: 1,
  displayId: 'WEB-1',
  title: testCaseFixture.title,
  description: testCaseFixture.description,
  preconditions: testCaseFixture.preconditions,
  postconditions: null,
  priority: testCaseFixture.priority,
  severity: testCaseFixture.severity,
  type: testCaseFixture.type,
  automationStatus: testCaseFixture.automationStatus,
  estimatedDurationSeconds: 180,
  position: 0,
  currentStatus: CurrentRunCaseStatus.Untested,
  createdAt: testCaseFixture.createdAt,
  updatedAt: testCaseFixture.updatedAt,
  steps: [
    {
      id: 'run-step-1',
      testRunCaseId: 'run-case-1',
      sourceTestStepId: 'step-1',
      position: 0,
      action: 'Открыть форму входа',
      testData: 'qa@example.com',
      expectedResult: 'Форма отображается',
      createdAt: testCaseFixture.createdAt,
      updatedAt: testCaseFixture.updatedAt,
    },
  ],
};
